import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Slidelang",
  description: "Decks as code, generated by Claude",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
